// file: src/lib/db/contraindications.ts — 50 条硬编码禁忌规则（CLAUDE.md §11.3 + §11.11）
// 数据来源：gpt烘焙方案.md §2.2 表，20 题 Demo 种子问题 Q1–Q20 的主 L2 判定骨架
//
// 合规红线：
// - CLAUDE.md §11.3：critical-indicator 硬编码，不得依赖 LLM 推理
// - CLAUDE.md §11.4：每条规则必须挂 SourceRef，严禁空
// - CLAUDE.md §11.11：pharmacistReviewed !== true 的规则触发后，DemoBannerInjector 挂横幅
// - 50 条全部以 pharmacistReviewed=false 起步（药剂师 outreach 仍在进行，CLAUDE.md §16）
//
// 层级定位：L1 静态数据，无 runtime 依赖、无副作用；供 L2 SafetyJudgment 按 (substanceA.id, substanceB.id) 查索

import 'server-only';
import type { Contraindication, Substance } from '@/lib/types/interaction';
import type { SourceRef } from '@/lib/types/sourceRef';

// ---- 构建期常量 ----
const RETRIEVED_AT = '2026-04-19';

/** 所有规则共享的源类型；id 在 build 时填入单条规则的 id */
const ref = (id: string, url?: string): SourceRef => ({
  source: 'hardcoded-contraindication',
  id,
  url,
  retrievedAt: RETRIEVED_AT,
});

// ---- Substance 工厂（按 interaction.ts §SubstanceKind 8 分类）----
const supp = (id: string, nameZh?: string, nameEn?: string): Substance => ({ id, kind: 'supplement', nameZh, nameEn });
const drug = (id: string, nameZh?: string, nameEn?: string): Substance => ({ id, kind: 'drug', nameZh, nameEn });
const drugClass = (id: string, nameZh?: string): Substance => ({ id, kind: 'drugClass', nameZh });
const condition = (id: string, nameZh?: string): Substance => ({ id, kind: 'condition', nameZh });
const gene = (id: string, nameZh?: string): Substance => ({ id, kind: 'gene', nameZh });
const specialGroup = (id: string, nameZh?: string): Substance => ({ id, kind: 'specialGroup', nameZh });
const timing = (id: string, nameZh?: string): Substance => ({ id, kind: 'usageTiming', nameZh });
const strategy = (id: string, nameZh?: string): Substance => ({ id, kind: 'usageStrategy', nameZh });

// ---- 50 条规则 ----
export const CONTRAINDICATIONS: Contraindication[] = [
  {
    id: 'vm-rule-fishoil-ssri-highdose',
    substanceA: supp('fish-oil', '鱼油'),
    substanceB: drugClass('ssri-use', 'SSRI 抗抑郁药'),
    severity: 'yellow',
    reasonCode: 'serotonergic_synergy_high_dose',
    reason: '高剂量鱼油与 SSRI 并用需警惕出血/5-HT 协同',
    doseThreshold: '>3g/天',
    sourceRef: ref('vm-rule-fishoil-ssri-highdose'),
    pharmacistReviewed: false,
  },
  {
    id: 'vm-rule-b6-ssri-highdose',
    substanceA: supp('vitamin-b6', '维生素 B6'),
    substanceB: drugClass('ssri-use', 'SSRI 抗抑郁药'),
    severity: 'yellow',
    reasonCode: 'b6_high_dose_neuro_risk',
    reason: '高剂量 B6 不建议与 SSRI 长期混用',
    doseThreshold: '>50mg/天长期',
    sourceRef: ref('vm-rule-b6-ssri-highdose'),
    pharmacistReviewed: false,
  },
  {
    id: 'vm-rule-fishoil-amlodipine',
    substanceA: supp('fish-oil', '鱼油'),
    substanceB: drug('amlodipine', '氨氯地平'),
    severity: 'yellow',
    reasonCode: 'bp_lowering_additive',
    reason: '与降压药同用可能叠加降压效应',
    sourceRef: ref('vm-rule-fishoil-amlodipine'),
    pharmacistReviewed: false,
  },
  {
    id: 'vm-rule-fishoil-antihypertensive-stack',
    substanceA: supp('fish-oil', '鱼油'),
    substanceB: drugClass('antihypertensive-stack', '多种降压药'),
    severity: 'yellow',
    reasonCode: 'bp_lowering_additive_polypharmacy',
    reason: '多种降压药并用时更需监测血压',
    sourceRef: ref('vm-rule-fishoil-antihypertensive-stack'),
    pharmacistReviewed: false,
  },
  {
    id: 'vm-rule-coq10-warfarin',
    substanceA: supp('coenzyme-q10', '辅酶 Q10'),
    substanceB: drug('warfarin', '华法林'),
    severity: 'red',
    reasonCode: 'vitamin_k_like_effect',
    reason: '可能降低华法林抗凝效果（类维 K 效应）',
    sourceRef: ref('vm-rule-coq10-warfarin'),
    pharmacistReviewed: false,
  },
  {
    id: 'vm-rule-fishoil-warfarin',
    substanceA: supp('fish-oil', '鱼油'),
    substanceB: drug('warfarin', '华法林'),
    severity: 'yellow',
    reasonCode: 'bleeding_risk_anticoagulant',
    reason: '抗凝药并用需警惕出血风险',
    sourceRef: ref('vm-rule-fishoil-warfarin'),
    pharmacistReviewed: false,
  },
  {
    id: 'vm-rule-vitamink-warfarin',
    substanceA: supp('vitamin-k', '维生素 K'),
    substanceB: drug('warfarin', '华法林'),
    severity: 'yellow',
    reasonCode: 'antagonize_warfarin',
    reason: '维 K 相关补充会影响 INR 稳定性',
    sourceRef: ref('vm-rule-vitamink-warfarin'),
    pharmacistReviewed: false,
  },
  {
    id: 'vm-rule-fishoil-active-hepatitis',
    substanceA: supp('fish-oil', '鱼油'),
    substanceB: condition('active-hepatitis', '活动期肝炎'),
    severity: 'yellow',
    reasonCode: 'hepatic_monitoring_needed',
    reason: '肝炎活动期需先核对 AST/ALT 与凝血功能',
    sourceRef: ref('vm-rule-fishoil-active-hepatitis'),
    pharmacistReviewed: false,
  },
  {
    id: 'vm-rule-fishoil-coagulopathy',
    substanceA: supp('fish-oil', '鱼油'),
    substanceB: condition('coagulation-abnormality', '凝血异常'),
    severity: 'yellow',
    reasonCode: 'bleeding_risk_liver_context',
    reason: '凝血异常背景下鱼油需谨慎',
    sourceRef: ref('vm-rule-fishoil-coagulopathy'),
    pharmacistReviewed: false,
  },
  {
    id: 'vm-rule-fishoil-apoe4-dhaheavy',
    substanceA: supp('fish-oil', '鱼油（高 DHA 配方）'),
    substanceB: gene('apoe4', 'APOE4'),
    severity: 'yellow',
    reasonCode: 'form_selection_gene_context',
    reason: 'APOE4 背景下优先避免盲目高 DHA 配方',
    sourceRef: ref('vm-rule-fishoil-apoe4-dhaheavy'),
    pharmacistReviewed: false,
  },
  {
    id: 'vm-rule-vitd-kidneystone',
    substanceA: supp('vitamin-d', '维生素 D'),
    substanceB: condition('kidney-stone-history', '肾结石史'),
    severity: 'yellow',
    reasonCode: 'stone_risk_hypercalciuria',
    reason: '促钙吸收，结石体质需控剂量',
    sourceRef: ref('vm-rule-vitd-kidneystone'),
    pharmacistReviewed: false,
  },
  {
    id: 'vm-rule-calcium-kidneystone',
    substanceA: supp('calcium', '钙'),
    substanceB: condition('kidney-stone-history', '肾结石史'),
    severity: 'yellow',
    reasonCode: 'stone_risk_total_calcium_load',
    reason: '结石体质避免额外高钙负荷',
    sourceRef: ref('vm-rule-calcium-kidneystone'),
    pharmacistReviewed: false,
  },
  {
    id: 'vm-rule-vitc-kidneystone-highdose',
    substanceA: supp('vitamin-c', '维生素 C'),
    substanceB: condition('kidney-stone-history', '肾结石史'),
    severity: 'yellow',
    reasonCode: 'oxalate_stone_risk',
    reason: '高剂量维 C 增加草酸盐负担',
    doseThreshold: '>1g/天',
    sourceRef: ref('vm-rule-vitc-kidneystone-highdose'),
    pharmacistReviewed: false,
  },
  {
    id: 'vm-rule-magnesium-oxide-gastriculcer',
    substanceA: supp('magnesium', '氧化镁'),
    substanceB: condition('gastric-ulcer', '胃溃疡'),
    severity: 'yellow',
    reasonCode: 'poor_absorption_osmotic_diarrhea',
    reason: '氧化镁刺激性强、易腹泻，胃溃疡不宜',
    sourceRef: ref('vm-rule-magnesium-oxide-gastriculcer'),
    pharmacistReviewed: false,
  },
  {
    id: 'vm-rule-magnesium-oxide-gi-sensitive',
    substanceA: supp('magnesium', '氧化镁'),
    substanceB: condition('gastric-sensitivity', '胃肠敏感'),
    severity: 'yellow',
    reasonCode: 'gi_irritation_form_specific',
    reason: '胃肠敏感人群不优先氧化镁',
    sourceRef: ref('vm-rule-magnesium-oxide-gi-sensitive'),
    pharmacistReviewed: false,
  },
  {
    id: 'vm-rule-magnesium-citrate-diarrhea-prone',
    substanceA: supp('magnesium', '柠檬酸镁'),
    substanceB: condition('diarrhea-prone', '易腹泻体质'),
    severity: 'yellow',
    reasonCode: 'osmotic_laxation_form_specific',
    reason: '柠檬酸镁偏通便，腹泻体质慎用',
    sourceRef: ref('vm-rule-magnesium-citrate-diarrhea-prone'),
    pharmacistReviewed: false,
  },
  {
    id: 'vm-rule-chromium-metformin',
    substanceA: supp('chromium', '铬'),
    substanceB: drug('metformin', '二甲双胍'),
    severity: 'yellow',
    reasonCode: 'glucose_lowering_additive',
    reason: '与降糖药叠加需防低血糖',
    sourceRef: ref('vm-rule-chromium-metformin'),
    pharmacistReviewed: false,
  },
  {
    id: 'vm-rule-cinnamon-metformin',
    substanceA: supp('cinnamon', '肉桂'),
    substanceB: drug('metformin', '二甲双胍'),
    severity: 'yellow',
    reasonCode: 'glucose_lowering_additive',
    reason: '肉桂与二甲双胍叠加需监测血糖',
    sourceRef: ref('vm-rule-cinnamon-metformin'),
    pharmacistReviewed: false,
  },
  {
    id: 'vm-rule-chromium-diabetes-medications',
    substanceA: supp('chromium', '铬'),
    substanceB: drugClass('diabetes-medications', '降糖药集合'),
    severity: 'yellow',
    reasonCode: 'glucose_lowering_additive_polypharmacy',
    reason: '与降糖药并用时需评估起始剂量与监测频率',
    sourceRef: ref('vm-rule-chromium-diabetes-medications'),
    pharmacistReviewed: false,
  },
  {
    id: 'vm-rule-cinnamon-diabetes-medications',
    substanceA: supp('cinnamon', '肉桂'),
    substanceB: drugClass('diabetes-medications', '降糖药集合'),
    severity: 'yellow',
    reasonCode: 'glucose_lowering_additive_polypharmacy',
    reason: '与降糖药叠加有低血糖可能',
    sourceRef: ref('vm-rule-cinnamon-diabetes-medications'),
    pharmacistReviewed: false,
  },
  {
    id: 'vm-rule-calcium-levothyroxine',
    substanceA: supp('calcium', '钙'),
    substanceB: drug('levothyroxine', '左甲状腺素（优甲乐）'),
    severity: 'yellow',
    reasonCode: 'reduced_absorption_levothyroxine',
    reason: '钙会影响优甲乐吸收，需间隔 4 小时服用',
    sourceRef: ref('vm-rule-calcium-levothyroxine'),
    pharmacistReviewed: false,
  },
  {
    id: 'vm-rule-iron-levothyroxine',
    substanceA: supp('iron', '铁'),
    substanceB: drug('levothyroxine', '左甲状腺素（优甲乐）'),
    severity: 'yellow',
    reasonCode: 'reduced_absorption_levothyroxine',
    reason: '铁剂也会影响优甲乐吸收，需间隔 4 小时',
    sourceRef: ref('vm-rule-iron-levothyroxine'),
    pharmacistReviewed: false,
  },
  {
    id: 'vm-rule-vitd-pregnancy',
    substanceA: supp('vitamin-d', '维生素 D'),
    substanceB: specialGroup('pregnancy', '孕期'),
    severity: 'yellow',
    reasonCode: 'pregnancy_requires_medical_confirmation',
    reason: '孕期维 D 需按血检与产科建议调整',
    sourceRef: ref('vm-rule-vitd-pregnancy'),
    pharmacistReviewed: false,
  },
  {
    id: 'vm-rule-vitamina-pregnancy-highdose',
    substanceA: supp('vitamin-a', '维生素 A（预成型 / retinol）'),
    substanceB: specialGroup('pregnancy', '孕期'),
    severity: 'red',
    reasonCode: 'retinol_pregnancy_teratogenicity',
    reason: '高剂量预成型维 A 孕期禁自行补（致畸风险）',
    doseThreshold: '>3000 mcg RAE/天',
    sourceRef: ref('vm-rule-vitamina-pregnancy-highdose'),
    pharmacistReviewed: false,
  },
  {
    id: 'vm-rule-iodine-thyroid-disorder',
    substanceA: supp('iodine', '碘'),
    substanceB: condition('thyroid-disorder', '甲状腺疾病'),
    severity: 'yellow',
    reasonCode: 'thyroid_axis_caution',
    reason: '甲状腺疾病背景下高碘补充需谨慎',
    sourceRef: ref('vm-rule-iodine-thyroid-disorder'),
    pharmacistReviewed: false,
  },
  {
    id: 'vm-rule-fishoil-empty-no-fat-meal',
    substanceA: supp('fish-oil', '鱼油'),
    substanceB: timing('no-fat-meal', '空腹或无脂餐'),
    severity: 'yellow',
    reasonCode: 'reduced_absorption_fat_soluble_context',
    reason: '空腹/无脂餐同服影响吸收与耐受',
    sourceRef: ref('vm-rule-fishoil-empty-no-fat-meal'),
    pharmacistReviewed: false,
  },
  {
    id: 'vm-rule-vitd-no-fat-meal',
    substanceA: supp('vitamin-d', '维生素 D'),
    substanceB: timing('no-fat-meal', '空腹或无脂餐'),
    severity: 'yellow',
    reasonCode: 'reduced_absorption_fat_soluble_context',
    reason: '无脂餐下维 D 吸收不稳',
    sourceRef: ref('vm-rule-vitd-no-fat-meal'),
    pharmacistReviewed: false,
  },
  {
    id: 'vm-rule-magnesium-morning-sedation-goal',
    substanceA: supp('magnesium', '镁'),
    substanceB: timing('daytime-use-for-sleep', '助眠目标却在白天服用'),
    severity: 'yellow',
    reasonCode: 'timing_goal_mismatch',
    reason: '助眠目标下不建议把主剂量放在早晨',
    sourceRef: ref('vm-rule-magnesium-morning-sedation-goal'),
    pharmacistReviewed: false,
  },
  {
    id: 'vm-rule-bcomplex-night-use',
    substanceA: supp('vitamin-b-complex', '维 B 复合'),
    substanceB: timing('bedtime-use', '睡前服用'),
    severity: 'yellow',
    reasonCode: 'timing_goal_mismatch',
    reason: '晚间大剂量 B 复合不利于睡眠',
    sourceRef: ref('vm-rule-bcomplex-night-use'),
    pharmacistReviewed: false,
  },
  {
    id: 'vm-rule-calcium-high-single-dose',
    substanceA: supp('calcium', '钙'),
    substanceB: strategy('single-dose-over-500mg', '单次剂量 >500mg'),
    severity: 'yellow',
    reasonCode: 'single_dose_absorption_drop',
    reason: '单次高钙负荷吸收率下降，建议拆分',
    doseThreshold: '>500mg/次',
    sourceRef: ref('vm-rule-calcium-high-single-dose'),
    pharmacistReviewed: false,
  },
  {
    id: 'vm-rule-iron-coffee-window',
    substanceA: supp('iron', '铁'),
    substanceB: timing('coffee-window', '咖啡服用窗口'),
    severity: 'yellow',
    reasonCode: 'coffee_reduces_iron_absorption',
    reason: '咖啡显著影响铁吸收，需间隔 1–2 小时',
    sourceRef: ref('vm-rule-iron-coffee-window'),
    pharmacistReviewed: false,
  },
  {
    id: 'vm-rule-calcium-coffee-window',
    substanceA: supp('calcium', '钙'),
    substanceB: timing('coffee-window', '咖啡服用窗口'),
    severity: 'yellow',
    reasonCode: 'coffee_reduces_calcium_absorption',
    reason: '咖啡与钙同窗影响吸收',
    sourceRef: ref('vm-rule-calcium-coffee-window'),
    pharmacistReviewed: false,
  },
  {
    id: 'vm-rule-bcomplex-coffee-window',
    substanceA: supp('vitamin-b-complex', '维 B 复合'),
    substanceB: timing('coffee-window', '咖啡服用窗口'),
    severity: 'yellow',
    reasonCode: 'coffee_reduces_b_absorption_context',
    reason: '咖啡下 B 族体验较差',
    sourceRef: ref('vm-rule-bcomplex-coffee-window'),
    pharmacistReviewed: false,
  },
  {
    id: 'vm-rule-iron-green-tea-window',
    substanceA: supp('iron', '铁'),
    substanceB: timing('green-tea-window', '绿茶服用窗口'),
    severity: 'yellow',
    reasonCode: 'tea_polyphenol_reduces_iron',
    reason: '绿茶影响非血红素铁吸收，建议间隔 2 小时',
    sourceRef: ref('vm-rule-iron-green-tea-window'),
    pharmacistReviewed: false,
  },
  {
    id: 'vm-rule-iron-longterm-highdose',
    substanceA: supp('iron', '铁'),
    substanceB: strategy('long-term-high-dose', '长期高剂量'),
    severity: 'yellow',
    reasonCode: 'iron_long_term_requires_reassessment',
    reason: '高剂量铁不宜长期自行补，3–6 月复评',
    sourceRef: ref('vm-rule-iron-longterm-highdose'),
    pharmacistReviewed: false,
  },
  {
    id: 'vm-rule-zinc-longterm-highdose',
    substanceA: supp('zinc', '锌'),
    substanceB: strategy('long-term-high-dose', '长期高剂量'),
    severity: 'yellow',
    reasonCode: 'zinc_long_term_requires_reassessment',
    reason: '高剂量锌长期用需评估铜缺乏风险',
    doseThreshold: '>40mg/天长期',
    sourceRef: ref('vm-rule-zinc-longterm-highdose'),
    pharmacistReviewed: false,
  },
  {
    id: 'vm-rule-vitd-longterm-highdose',
    substanceA: supp('vitamin-d', '维生素 D'),
    substanceB: strategy('long-term-high-dose', '长期高剂量'),
    severity: 'yellow',
    reasonCode: 'fat_soluble_accumulation_risk',
    reason: '维 D 长期高剂量需复评 25(OH)D 与钙',
    sourceRef: ref('vm-rule-vitd-longterm-highdose'),
    pharmacistReviewed: false,
  },
  {
    id: 'vm-rule-vitamina-longterm-highdose',
    substanceA: supp('vitamin-a', '维生素 A（预成型 / retinol）'),
    substanceB: strategy('long-term-high-dose', '长期高剂量'),
    severity: 'red',
    reasonCode: 'fat_soluble_accumulation_high_risk',
    reason: '预成型维 A 长期高剂量风险高（脂溶性蓄积）',
    sourceRef: ref('vm-rule-vitamina-longterm-highdose'),
    pharmacistReviewed: false,
  },
  {
    id: 'vm-rule-vitamine-longterm-highdose',
    substanceA: supp('vitamin-e', '维生素 E'),
    substanceB: strategy('long-term-high-dose', '长期高剂量'),
    severity: 'yellow',
    reasonCode: 'fat_soluble_accumulation_risk',
    reason: '高剂量维 E 长期使用需评估（合并抗凝药更需谨慎）',
    sourceRef: ref('vm-rule-vitamine-longterm-highdose'),
    pharmacistReviewed: false,
  },
  {
    id: 'vm-rule-selenium-longterm-highdose',
    substanceA: supp('selenium', '硒'),
    substanceB: strategy('long-term-high-dose', '长期高剂量'),
    severity: 'yellow',
    reasonCode: 'selenium_excess_reassessment',
    reason: '硒长期高剂量需复评（关注指甲、胃肠副作用）',
    sourceRef: ref('vm-rule-selenium-longterm-highdose'),
    pharmacistReviewed: false,
  },
  {
    id: 'vm-rule-iodine-pregnancy-highdose',
    substanceA: supp('iodine', '碘'),
    substanceB: specialGroup('pregnancy', '孕期'),
    severity: 'yellow',
    reasonCode: 'iodine_pregnancy_requires_confirmation',
    reason: '孕期高碘不建议自行加量',
    sourceRef: ref('vm-rule-iodine-pregnancy-highdose'),
    pharmacistReviewed: false,
  },
  {
    id: 'vm-rule-choline-pregnancy-self-escalation',
    substanceA: supp('choline', '胆碱'),
    substanceB: specialGroup('pregnancy', '孕期'),
    severity: 'yellow',
    reasonCode: 'pregnancy_self_escalation_caution',
    reason: '胆碱可补，但不建议孕期自行高量叠加',
    sourceRef: ref('vm-rule-choline-pregnancy-self-escalation'),
    pharmacistReviewed: false,
  },
  {
    id: 'vm-rule-b12-selfstart-polystack',
    substanceA: supp('vitamin-b12', '维生素 B12'),
    substanceB: strategy('polystack-self-start', '多补剂同时起步'),
    severity: 'yellow',
    reasonCode: 'stack_complexity_first_one_only',
    reason: '"全都要吃" 场景不建议一上来就高堆栈',
    sourceRef: ref('vm-rule-b12-selfstart-polystack'),
    pharmacistReviewed: false,
  },
  {
    id: 'vm-rule-folate-selfstart-polystack',
    substanceA: supp('folate', '叶酸'),
    substanceB: strategy('polystack-self-start', '多补剂同时起步'),
    severity: 'yellow',
    reasonCode: 'stack_complexity_first_one_only',
    reason: '起始应先看目标与既有用药（尤其备孕/非备孕需分开）',
    sourceRef: ref('vm-rule-folate-selfstart-polystack'),
    pharmacistReviewed: false,
  },
  {
    id: 'vm-rule-magnesium-selfstart-polystack',
    substanceA: supp('magnesium', '镁'),
    substanceB: strategy('polystack-self-start', '多补剂同时起步'),
    severity: 'yellow',
    reasonCode: 'stack_complexity_first_one_only',
    reason: '先按单一目标起步更稳',
    sourceRef: ref('vm-rule-magnesium-selfstart-polystack'),
    pharmacistReviewed: false,
  },
  {
    id: 'vm-rule-probiotic-selfstart-polystack',
    substanceA: supp('probiotic', '益生菌'),
    substanceB: strategy('polystack-self-start', '多补剂同时起步'),
    severity: 'yellow',
    reasonCode: 'stack_complexity_first_one_only',
    reason: '益生菌也不建议与 5+ 新补剂同启，给 2–4 周观察期',
    sourceRef: ref('vm-rule-probiotic-selfstart-polystack'),
    pharmacistReviewed: false,
  },
  {
    id: 'vm-rule-vitc-selfstart-polystack',
    substanceA: supp('vitamin-c', '维生素 C'),
    substanceB: strategy('polystack-self-start', '多补剂同时起步'),
    severity: 'yellow',
    reasonCode: 'stack_complexity_first_one_only',
    reason: '入门补充不要多剂并起',
    sourceRef: ref('vm-rule-vitc-selfstart-polystack'),
    pharmacistReviewed: false,
  },
  {
    id: 'vm-rule-zinc-iron-same-window',
    substanceA: supp('zinc', '锌'),
    substanceB: timing('iron-window-overlap', '铁服用窗口重叠'),
    severity: 'yellow',
    reasonCode: 'mineral_competition_absorption',
    reason: '铁锌同窗影响吸收体验，建议分次',
    sourceRef: ref('vm-rule-zinc-iron-same-window'),
    pharmacistReviewed: false,
  },
  {
    id: 'vm-rule-calcium-iron-same-window',
    substanceA: supp('calcium', '钙'),
    substanceB: timing('iron-window-overlap', '铁服用窗口重叠'),
    severity: 'yellow',
    reasonCode: 'mineral_competition_absorption',
    reason: '钙铁同窗不优先（与早餐/咖啡场景组合更需错开）',
    sourceRef: ref('vm-rule-calcium-iron-same-window'),
    pharmacistReviewed: false,
  },
  {
    id: 'vm-rule-calcium-magnesium-highdose-window',
    substanceA: supp('calcium', '钙'),
    substanceB: timing('magnesium-highdose-window', '同时高剂量镁'),
    severity: 'yellow',
    reasonCode: 'high_mineral_load_split_dose',
    reason: '高剂量矿物堆叠建议拆分服用',
    sourceRef: ref('vm-rule-calcium-magnesium-highdose-window'),
    pharmacistReviewed: false,
  },
];

// ---- 运行时索引：二元组 (a.id, b.id) → 规则 ----
export const CONTRAINDICATION_BY_PAIR: ReadonlyMap<string, Contraindication> = new Map(
  CONTRAINDICATIONS.map((r) => [`${r.substanceA.id}|${r.substanceB.id}`, r]),
);

/** 按 reasonCode 取规则，供 compliance DemoBannerInjector / L3 templateFallback 反查 */
export const CONTRAINDICATION_BY_REASON_CODE: ReadonlyMap<string, Contraindication> = new Map(
  CONTRAINDICATIONS.map((r) => [r.reasonCode, r]),
);
